//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkOutDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expens()
        {
            this.TransferStations = new HashSet<TransferStation>();
        }
    
        public int ID { get; set; }
        public string DisposalCost { get; set; }
        public string Distance { get; set; }
        public string Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStation> TransferStations { get; set; }
    }
}
