//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkOutDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string JobType { get; set; }
        public string SourceOfOrdering { get; set; }
        public string HearingSource { get; set; }
        public string OrderNotes { get; set; }
        public string Status { get; set; }
        public System.DateTime DeliveryDateTime { get; set; }
        public Nullable<System.DateTime> PickupDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Bin Bin { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual TransferStation TransferStation { get; set; }
    }
}
