//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkOutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        public int Id { get; set; }
        public string BinSize { get; set; }
        public double FlatRate { get; set; }
        public double MinTonnageAwarded { get; set; }
        public double MaxRentalDuration { get; set; }
        public string Status { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
