//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkOutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public double HST { get; set; }
        public Nullable<double> FuelSurcharge { get; set; }
        public double SubTotal { get; set; }
        public Nullable<double> OverWeight { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
