//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunkOutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferStation
    {
        public int Id { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string HoursOfOperations { get; set; }
        public string Notes { get; set; }
        public string Rate { get; set; }
        public string Terms { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Expense Expense { get; set; }
    }
}
